# Generated by Django 3.2.23 on 2024-01-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wishlists", "0004_auto_20220328_0939"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="is_wishlist",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="line",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="wishlistsharedemail",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
