# Generated by Django 3.2.23 on 2024-01-25 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wishlists", "0006_line_is_wishlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlist",
            name="is_wishlist",
        ),
    ]
