# Generated by Django 4.2.6 on 2023-10-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="otp_verify",
            field=models.BooleanField(default=False),
        ),
    ]
