# Generated by Django 4.2.6 on 2024-03-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0008_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientdetails",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female")],
                default="Male",
                max_length=10,
                null=True,
            ),
        ),
    ]
