# Generated by Django 4.2.6 on 2024-04-02 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0011_voucheruser"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientdetails",
            name="current_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
