# Generated by Django 4.2.6 on 2024-04-03 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0012_clientdetails_current_date"),
        ("useraccount", "0012_vocherloginconnect"),
    ]

    operations = []
