# Generated by Django 4.2.6 on 2024-04-29 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0013_merge_20240403_0924"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["-created_at"]},
        ),
    ]
