# Generated by Django 4.2.6 on 2024-05-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0014_alter_contact_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadProductJSon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upload_json", models.JSONField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
