# Generated by Django 4.2.6 on 2024-05-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0016_intermediateproducttableparent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="Parent_UPC",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="Specification",
            field=models.TextField(max_length=254),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="first_category",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="gst_rate",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="is_discountable",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="is_public",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="low_stock_threshold",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="product_type",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="standard_rate",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="supplier",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="title",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="upc",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="intermediateproducttableparent",
            name="Specification",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="intermediateproducttableparent",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="intermediateproducttableparent",
            name="hsn_code",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="intermediateproducttableparent",
            name="product_type",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="intermediateproducttableparent",
            name="title",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="intermediateproducttableparent",
            name="upc",
            field=models.CharField(max_length=254),
        ),
    ]
