# Generated by Django 4.2.6 on 2024-05-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0017_alter_intermediateproducttablechild_parent_upc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="Parent_UPC",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="Specification",
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="attributes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="best_seller",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="brand",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="discount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="first_category",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="gst_rate",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="is_discountable",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="is_public",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="length",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="low_stock_threshold",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="mrp",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="num_in_stock",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="product_type",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="recommended_products",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="shipment_dimensions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="standard_rate",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="structure",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="supplier",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="title",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="upc",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="weight",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttablechild",
            name="width",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttableparent",
            name="Specification",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttableparent",
            name="attributes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttableparent",
            name="best_seller",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttableparent",
            name="brand",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttableparent",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttableparent",
            name="first_category",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttableparent",
            name="hsn_code",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttableparent",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttableparent",
            name="is_discountable",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttableparent",
            name="is_public",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttableparent",
            name="num_in_stock",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttableparent",
            name="product_type",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttableparent",
            name="recommended_products",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttableparent",
            name="standard_rate",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttableparent",
            name="structure",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttableparent",
            name="title",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="intermediateproducttableparent",
            name="upc",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
