# Generated by Django 4.2.6 on 2024-05-10 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0018_alter_intermediateproducttablechild_parent_upc_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intermediateproducttablechild",
            name="shipment_dimensions",
        ),
    ]
