# Generated by Django 4.2.6 on 2024-05-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "useraccount",
            "0019_remove_intermediateproducttablechild_shipment_dimensions",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="intermediateproducttablechild",
            name="hsn_code",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
