# Generated by Django 4.2.6 on 2024-05-22 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0020_intermediateproducttablechild_hsn_code"),
    ]

    operations = [
        migrations.DeleteModel(
            name="IntermediateProductTableParent",
        ),
    ]
