# Generated by Django 4.2.6 on 2024-05-23 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0022_clientemailverify"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientemailverify",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clientemailverify",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
