# Generated by Django 4.2.6 on 2024-05-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0023_clientemailverify_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="intermediateproducttablechild",
            name="created_status",
            field=models.CharField(default="Pending Creation", max_length=100),
        ),
    ]
