# Generated by Django 4.2.6 on 2024-05-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "useraccount",
            "0025_rename_created_status_intermediateproducttablechild_product_status",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestBussinessRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary_contact_person",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "designation",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
            ],
        ),
    ]
