# Generated by Django 4.2.6 on 2024-05-28 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0026_requestbussinessregister"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingAlternativePersonDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "designation",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OnboardingGstVerify",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gst_number", models.CharField(max_length=50)),
                (
                    "bussiness_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "first_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "second_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("postal_code", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                ("date_of_establishment", models.DateTimeField(blank=True, null=True)),
                (
                    "request_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="useraccount.requestbussinessregister",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OnboardingBussinessDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_company_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "second_company_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "industry_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "website_link",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "onboarding_gst_verify",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="useraccount.onboardinggstverify",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OnboardingBankDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=150, null=True)),
                ("bank_acc_no", models.CharField(max_length=150)),
                (
                    "bank_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "billing_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "upload_pan",
                    models.ImageField(blank=True, null=True, upload_to="Onboarding/"),
                ),
                (
                    "upload_gst",
                    models.ImageField(blank=True, null=True, upload_to="Onboarding/"),
                ),
                (
                    "onboarding_alternative_perDetails",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="useraccount.onboardingalternativepersondetails",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="onboardingalternativepersondetails",
            name="onboarding_bussiness_details",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="useraccount.onboardingbussinessdetails",
            ),
        ),
    ]
