# Generated by Django 4.2.6 on 2024-05-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0027_onboardingalternativepersondetails_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboardinggstverify",
            name="date_of_establishment",
            field=models.DateField(blank=True, null=True),
        ),
    ]
