# Generated by Django 4.2.6 on 2024-05-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0028_alter_onboardinggstverify_date_of_establishment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboardinggstverify",
            name="gst_number",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
