# Generated by Django 4.2.6 on 2024-05-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0029_alter_onboardinggstverify_gst_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboardingalternativepersondetails",
            name="city",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="onboardingalternativepersondetails",
            name="country",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="onboardingalternativepersondetails",
            name="first_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="onboardingalternativepersondetails",
            name="postal_code",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="onboardingalternativepersondetails",
            name="second_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="onboardingalternativepersondetails",
            name="state",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="onboardingbankdetails",
            name="ifsc_code",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
