# Generated by Django 4.2.6 on 2024-05-31 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0030_onboardingalternativepersondetails_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientdetails",
            name="alter_city",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="alter_country",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="alter_designation",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="alter_email",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="alter_first_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="alter_mobile_number",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="alter_person_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="alter_postal_code",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="alter_second_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="alter_state",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="bank_acc_no",
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="bank_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="bank_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="billing_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="date_of_establishment",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="first_company_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="ifsc_code",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="industry_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="second_company_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="upload_gst",
            field=models.ImageField(blank=True, null=True, upload_to="Onboarding/"),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="upload_pan",
            field=models.ImageField(blank=True, null=True, upload_to="Onboarding/"),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="website_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="onboardinggstverify",
            name="pancard_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
