# Generated by Django 4.2.6 on 2024-05-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "useraccount",
            "0031_clientdetails_alter_city_clientdetails_alter_country_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="clientdetails",
            name="designation",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="primary_contact_person",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
