# Generated by Django 4.2.6 on 2024-06-12 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0033_clientdetails_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniqueStrings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_string", models.CharField(max_length=100)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="useraccount.clientdetails",
                    ),
                ),
            ],
        ),
    ]
