# Generated by Django 4.2.6 on 2024-06-13 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0034_uniquestrings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uniquestrings",
            name="client",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client",
                to="useraccount.clientdetails",
            ),
        ),
    ]
