# Generated by Django 4.2.6 on 2024-06-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0035_alter_uniquestrings_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="uniquestrings",
            name="digit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
