# Generated by Django 4.2.6 on 2024-06-28 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0036_uniquestrings_digit"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductUploadErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("upload_count", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductUploadSuccesLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("upload_count", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="IntermediateProductTableSucces",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upc", models.CharField(blank=True, max_length=254, null=True)),
                ("hsn_code", models.CharField(blank=True, max_length=254, null=True)),
                ("title", models.CharField(blank=True, max_length=254, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "Specification",
                    models.TextField(blank=True, max_length=254, null=True),
                ),
                ("image", models.TextField(blank=True, null=True)),
                (
                    "product_type",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("is_public", models.CharField(blank=True, max_length=254, null=True)),
                (
                    "is_discountable",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                (
                    "best_seller",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "standard_rate",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                (
                    "num_in_stock",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("brand", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "first_category",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("attributes", models.TextField(blank=True, null=True)),
                ("Parent_UPC", models.CharField(blank=True, max_length=254, null=True)),
                ("structure", models.CharField(blank=True, max_length=100, null=True)),
                ("recommended_products", models.TextField(blank=True, null=True)),
                ("length", models.IntegerField(blank=True, null=True)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("weight", models.IntegerField(blank=True, null=True)),
                ("supplier", models.CharField(blank=True, max_length=254, null=True)),
                (
                    "low_stock_threshold",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("mrp", models.IntegerField(blank=True, null=True)),
                ("discount", models.IntegerField(blank=True, null=True)),
                ("price", models.IntegerField(blank=True, null=True)),
                ("gst_rate", models.CharField(blank=True, max_length=254, null=True)),
                (
                    "log_date_conn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log",
                        to="useraccount.productuploadsucceslog",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntermediateProductTableError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upc", models.CharField(blank=True, max_length=254, null=True)),
                ("hsn_code", models.CharField(blank=True, max_length=254, null=True)),
                ("title", models.CharField(blank=True, max_length=254, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "Specification",
                    models.TextField(blank=True, max_length=254, null=True),
                ),
                ("image", models.TextField(blank=True, null=True)),
                (
                    "product_type",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("is_public", models.CharField(blank=True, max_length=254, null=True)),
                (
                    "is_discountable",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                (
                    "best_seller",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "standard_rate",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                (
                    "num_in_stock",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("brand", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "first_category",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("attributes", models.TextField(blank=True, null=True)),
                ("Parent_UPC", models.CharField(blank=True, max_length=254, null=True)),
                ("structure", models.CharField(blank=True, max_length=100, null=True)),
                ("recommended_products", models.TextField(blank=True, null=True)),
                ("length", models.IntegerField(blank=True, null=True)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("weight", models.IntegerField(blank=True, null=True)),
                ("supplier", models.CharField(blank=True, max_length=254, null=True)),
                (
                    "low_stock_threshold",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("mrp", models.IntegerField(blank=True, null=True)),
                ("discount", models.IntegerField(blank=True, null=True)),
                ("price", models.IntegerField(blank=True, null=True)),
                ("gst_rate", models.CharField(blank=True, max_length=254, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                (
                    "log_date_conn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log",
                        to="useraccount.productuploaderrorlog",
                    ),
                ),
            ],
        ),
    ]
