# Generated by Django 4.2.6 on 2024-07-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0039_alter_uniquestrings_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpdateErpstatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upc", models.CharField(max_length=100)),
                ("update_erp", models.BooleanField(default=False)),
            ],
        ),
    ]
