# Generated by Django 4.2.6 on 2024-07-13 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0040_updateerpstatus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientdetails",
            name="bank_acc_no",
        ),
        migrations.RemoveField(
            model_name="clientdetails",
            name="bank_address",
        ),
        migrations.RemoveField(
            model_name="clientdetails",
            name="bank_name",
        ),
        migrations.RemoveField(
            model_name="clientdetails",
            name="ifsc_code",
        ),
        migrations.RemoveField(
            model_name="onboardingbankdetails",
            name="bank_acc_no",
        ),
        migrations.RemoveField(
            model_name="onboardingbankdetails",
            name="bank_address",
        ),
        migrations.RemoveField(
            model_name="onboardingbankdetails",
            name="bank_name",
        ),
        migrations.RemoveField(
            model_name="onboardingbankdetails",
            name="ifsc_code",
        ),
        migrations.CreateModel(
            name="ClientRequestDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Requested", "Requested"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Requested",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "onboarding_alternative_perDetails",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="useraccount.onboardingalternativepersondetails",
                    ),
                ),
                (
                    "onboarding_bank_details",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="useraccount.onboardingbankdetails",
                    ),
                ),
                (
                    "onboarding_bussiness_details",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="useraccount.onboardingbussinessdetails",
                    ),
                ),
                (
                    "onboarding_gst_verify",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="useraccount.onboardinggstverify",
                    ),
                ),
                (
                    "request_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="useraccount.requestbussinessregister",
                    ),
                ),
            ],
        ),
    ]
