# Generated by Django 4.2.6 on 2024-07-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0041_remove_clientdetails_bank_acc_no_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientdetails",
            name="alter_designation",
        ),
        migrations.RemoveField(
            model_name="clientdetails",
            name="alter_email",
        ),
        migrations.RemoveField(
            model_name="clientdetails",
            name="alter_mobile_number",
        ),
        migrations.RemoveField(
            model_name="clientdetails",
            name="alter_person_name",
        ),
        migrations.RemoveField(
            model_name="onboardingalternativepersondetails",
            name="designation",
        ),
        migrations.RemoveField(
            model_name="onboardingalternativepersondetails",
            name="email",
        ),
        migrations.RemoveField(
            model_name="onboardingalternativepersondetails",
            name="mobile_number",
        ),
        migrations.RemoveField(
            model_name="onboardingalternativepersondetails",
            name="person_name",
        ),
        migrations.RemoveField(
            model_name="onboardinggstverify",
            name="bussiness_name",
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="authorization_letter",
            field=models.ImageField(blank=True, null=True, upload_to="Onboarding/"),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="cancelation_letter",
            field=models.ImageField(blank=True, null=True, upload_to="Onboarding/"),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="certificate_of_corporation",
            field=models.ImageField(blank=True, null=True, upload_to="Onboarding/"),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="msme",
            field=models.ImageField(blank=True, null=True, upload_to="Onboarding/"),
        ),
        migrations.AddField(
            model_name="onboardingbankdetails",
            name="authorization_letter",
            field=models.ImageField(blank=True, null=True, upload_to="Onboarding/"),
        ),
        migrations.AddField(
            model_name="onboardingbankdetails",
            name="cancelation_letter",
            field=models.ImageField(blank=True, null=True, upload_to="Onboarding/"),
        ),
        migrations.AddField(
            model_name="onboardingbankdetails",
            name="certificate_of_corporation",
            field=models.ImageField(blank=True, null=True, upload_to="Onboarding/"),
        ),
        migrations.AddField(
            model_name="onboardingbankdetails",
            name="msme",
            field=models.ImageField(blank=True, null=True, upload_to="Onboarding/"),
        ),
        migrations.AddField(
            model_name="requestbussinessregister",
            name="bussiness_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="clientdetails",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female")],
                default=" ",
                max_length=10,
                null=True,
            ),
        ),
    ]
