# Generated by Django 4.2.6 on 2024-07-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0043_alter_onboardinggstverify_gst_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="GetHelpOnHomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="GetHelpImage/"),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
