# Generated by Django 4.2.6 on 2024-08-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0044_gethelponhomepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="gethelponhomepage",
            name="read_status",
            field=models.BooleanField(default=False),
        ),
    ]
