# Generated by Django 4.2.6 on 2024-08-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0045_gethelponhomepage_read_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="onboardingalternativepersondetails",
            name="city",
        ),
        migrations.RemoveField(
            model_name="onboardingalternativepersondetails",
            name="country",
        ),
        migrations.RemoveField(
            model_name="onboardingalternativepersondetails",
            name="first_address",
        ),
        migrations.RemoveField(
            model_name="onboardingalternativepersondetails",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="onboardingalternativepersondetails",
            name="second_address",
        ),
        migrations.RemoveField(
            model_name="onboardingalternativepersondetails",
            name="state",
        ),
        migrations.AddField(
            model_name="onboardingalternativepersondetails",
            name="alternative_designation",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="onboardingalternativepersondetails",
            name="alternative_email",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="onboardingalternativepersondetails",
            name="alternative_mobile",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name="onboardingalternativepersondetails",
            name="alternative_person_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
