# Generated by Django 4.2.6 on 2024-08-07 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0046_remove_onboardingalternativepersondetails_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingCommunication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "communication_postal_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "communication_country",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "communication_state",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "communication_city",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="onboardingbankdetails",
            name="billing_address",
        ),
        migrations.CreateModel(
            name="OnboardingRegisteredAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "communication_postal_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "communication_country",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "communication_state",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "communication_city",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "onboarding_bussiness_details",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="useraccount.onboardingcommunication",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="onboardingcommunication",
            name="onboarding_bussiness_details",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="useraccount.onboardingbankdetails",
            ),
        ),
    ]
