# Generated by Django 4.2.6 on 2024-08-07 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0047_onboardingcommunication_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="onboardingcommunication",
            old_name="onboarding_bussiness_details",
            new_name="onboarding_bank_details",
        ),
        migrations.RenameField(
            model_name="onboardingregisteredaddress",
            old_name="onboarding_bussiness_details",
            new_name="onboarding_comm_details",
        ),
        migrations.RenameField(
            model_name="onboardingregisteredaddress",
            old_name="communication_city",
            new_name="reg_city",
        ),
        migrations.RenameField(
            model_name="onboardingregisteredaddress",
            old_name="communication_country",
            new_name="reg_country",
        ),
        migrations.RenameField(
            model_name="onboardingregisteredaddress",
            old_name="communication_postal_code",
            new_name="reg_postal_code",
        ),
        migrations.RenameField(
            model_name="onboardingregisteredaddress",
            old_name="communication_state",
            new_name="reg_state",
        ),
    ]
