# Generated by Django 4.2.6 on 2024-08-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "useraccount",
            "0048_rename_onboarding_bussiness_details_onboardingcommunication_onboarding_bank_details_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="onboardingcommunication",
            name="communication_address",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="onboardingregisteredaddress",
            name="reg_address",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
