# Generated by Django 4.2.6 on 2024-08-07 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0049_onboardingcommunication_communication_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="onboardingbankdetails",
            old_name="cancelation_letter",
            new_name="aadhar",
        ),
    ]
