# Generated by Django 4.2.6 on 2024-08-09 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0050_rename_cancelation_letter_onboardingbankdetails_aadhar"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientrequestdetails",
            name="onboarding_comm_ad",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="useraccount.onboardingcommunication",
            ),
        ),
        migrations.AddField(
            model_name="clientrequestdetails",
            name="onboarding_reg_ad",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="useraccount.onboardingregisteredaddress",
            ),
        ),
        migrations.AlterField(
            model_name="clientrequestdetails",
            name="onboarding_bank_details",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="useraccount.onboardingbankdetails",
            ),
        ),
    ]
