# Generated by Django 4.2.6 on 2024-08-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0051_clientrequestdetails_onboarding_comm_ad_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboardinggstverify",
            name="gst_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
