# Generated by Django 4.2.6 on 2024-08-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0053_alter_onboardinggstverify_gst_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientdetails",
            name="alter_city",
        ),
        migrations.RemoveField(
            model_name="clientdetails",
            name="alter_country",
        ),
        migrations.RemoveField(
            model_name="clientdetails",
            name="alter_first_address",
        ),
        migrations.RemoveField(
            model_name="clientdetails",
            name="alter_postal_code",
        ),
        migrations.RemoveField(
            model_name="clientdetails",
            name="alter_second_address",
        ),
        migrations.RemoveField(
            model_name="clientdetails",
            name="alter_state",
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="alternative_designation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="alternative_email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="alternative_mobile",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="alternative_person_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
