# Generated by Django 4.2.6 on 2024-08-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0054_remove_clientdetails_alter_city_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clientdetails",
            old_name="cancelation_letter",
            new_name="adhaar",
        ),
        migrations.RemoveField(
            model_name="clientdetails",
            name="billing_address",
        ),
    ]
