# Generated by Django 4.2.6 on 2024-08-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0055_rename_cancelation_letter_clientdetails_adhaar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucheruser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female")],
                max_length=10,
                null=True,
            ),
        ),
    ]
