# Generated by Django 4.2.6 on 2024-08-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0055_rename_cancelation_letter_clientdetails_adhaar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientdetails",
            name="communication_address",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="communication_city",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="communication_country",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="communication_postal_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="communication_state",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="reg_address",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="reg_city",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="reg_country",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="reg_postal_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="reg_state",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
