# Generated by Django 4.2.6 on 2024-08-24 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0056_alter_voucheruser_gender'),
        ('useraccount', '0056_clientdetails_communication_address_and_more'),
    ]

    operations = [
    ]
