# Generated by Django 4.2.6 on 2024-08-27 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0057_merge_20240824_1710"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutletAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outlet_postal_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "outlet_country",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "outlet_state",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "outlet_city",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "outlet_address",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WarehouseAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "warehouse_postal_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "warehouse_country",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "warehouse_state",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "warehouse_city",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "warehouse_address",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "onboarding_reg_details",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="useraccount.onboardingregisteredaddress",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="clientrequestdetails",
            name="onboarding_alternative_perDetails",
        ),
        migrations.RemoveField(
            model_name="onboardingbankdetails",
            name="onboarding_alternative_perDetails",
        ),
        migrations.RemoveField(
            model_name="onboardingbussinessdetails",
            name="second_company_type",
        ),
        migrations.RemoveField(
            model_name="onboardinggstverify",
            name="city",
        ),
        migrations.RemoveField(
            model_name="onboardinggstverify",
            name="country",
        ),
        migrations.RemoveField(
            model_name="onboardinggstverify",
            name="first_address",
        ),
        migrations.RemoveField(
            model_name="onboardinggstverify",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="onboardinggstverify",
            name="second_address",
        ),
        migrations.RemoveField(
            model_name="onboardinggstverify",
            name="state",
        ),
        migrations.AddField(
            model_name="onboardingbankdetails",
            name="onboarding_bussiness_details",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="useraccount.onboardingbussinessdetails",
            ),
        ),
        migrations.AlterField(
            model_name="clientrequestdetails",
            name="status",
            field=models.CharField(
                choices=[
                    ("Requested", "Requested"),
                    ("Accepted", "Accepted"),
                    ("Rejected", "Rejected"),
                    ("Hold", "Hold"),
                ],
                default="Requested",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="OnboardingAlternativePersonDetails",
        ),
        migrations.AddField(
            model_name="outletaddress",
            name="onboarding_warehouse_details",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="useraccount.warehouseaddress",
            ),
        ),
        migrations.AddField(
            model_name="clientrequestdetails",
            name="onboarding_OutletAddress_ad",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="useraccount.outletaddress",
            ),
        ),
        migrations.AddField(
            model_name="clientrequestdetails",
            name="onboarding_Warehouse_ad",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="useraccount.warehouseaddress",
            ),
        ),
    ]
