# Generated by Django 4.2.6 on 2024-08-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0058_outletaddress_warehouseaddress_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientdetails",
            name="address_line1",
        ),
        migrations.RemoveField(
            model_name="clientdetails",
            name="address_line2",
        ),
        migrations.RemoveField(
            model_name="clientdetails",
            name="alternative_designation",
        ),
        migrations.RemoveField(
            model_name="clientdetails",
            name="alternative_email",
        ),
        migrations.RemoveField(
            model_name="clientdetails",
            name="alternative_mobile",
        ),
        migrations.RemoveField(
            model_name="clientdetails",
            name="alternative_person_name",
        ),
        migrations.RemoveField(
            model_name="clientdetails",
            name="city",
        ),
        migrations.RemoveField(
            model_name="clientdetails",
            name="country",
        ),
        migrations.RemoveField(
            model_name="clientdetails",
            name="pin_code",
        ),
        migrations.RemoveField(
            model_name="clientdetails",
            name="second_company_type",
        ),
        migrations.RemoveField(
            model_name="clientdetails",
            name="state",
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="outlet_address",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="outlet_city",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="outlet_country",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="outlet_postal_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="outlet_state",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="wherehouse_address",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="wherehouse_city",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="wherehouse_country",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="wherehouse_postal_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="wherehouse_state",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
