# Generated by Django 4.2.6 on 2024-08-28 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0059_remove_clientdetails_address_line1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clientdetails",
            old_name="wherehouse_address",
            new_name="warehouse_address",
        ),
        migrations.RenameField(
            model_name="clientdetails",
            old_name="wherehouse_city",
            new_name="warehouse_city",
        ),
        migrations.RenameField(
            model_name="clientdetails",
            old_name="wherehouse_country",
            new_name="warehouse_country",
        ),
        migrations.RenameField(
            model_name="clientdetails",
            old_name="wherehouse_postal_code",
            new_name="warehouse_postal_code",
        ),
        migrations.RenameField(
            model_name="clientdetails",
            old_name="wherehouse_state",
            new_name="warehouse_state",
        ),
    ]
