# Generated by Django 4.2.6 on 2024-09-16 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "useraccount",
            "0060_rename_wherehouse_address_clientdetails_warehouse_address_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientdetails",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
