# Generated by Django 4.2.10 on 2024-02-29 03:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("MyNewsLetterApi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatemodel",
            name="message",
            field=tinymce.models.HTMLField(),
        ),
    ]
