# Generated by Django 4.2.6 on 2024-03-07 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MyNewsLetterApi", "0003_subscribermodel_current_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscribermodel",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="templatemodel",
            options={"ordering": ["id"]},
        ),
    ]
