# Generated by Django 4.2.6 on 2024-04-29 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MyNewsLetterApi", "0004_alter_subscribermodel_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscribermodel",
            options={"ordering": ["-current_date"]},
        ),
        migrations.AlterModelOptions(
            name="templatemodel",
            options={"ordering": ["-current_date"]},
        ),
    ]
