# Generated by Django 4.2.6 on 2024-01-16 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepageapi", "0004_bannermanagement"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bannermanagement",
        ),
    ]
