# Generated by Django 4.2.6 on 2024-05-09 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0031_product_featured_products"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailedOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=60)),
                ("order_failed_time", models.DateTimeField(auto_now_add=True)),
                ("order_failed_trace_back", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="StockSyncReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_stock", models.IntegerField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogue.product",
                    ),
                ),
            ],
        ),
    ]
