# Generated by Django 4.2.6 on 2024-05-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync_data_erp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stocksyncreport",
            name="updated_stock",
        ),
        migrations.AddField(
            model_name="stocksyncreport",
            name="inventory",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stocksyncreport",
            name="last_stock",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
