# Generated by Django 4.2.6 on 2024-05-31 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sync_data_erp", "0002_remove_stocksyncreport_updated_stock_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stocksyncreport",
            options={"ordering": ["-id"]},
        ),
    ]
