# Generated by Django 4.2.6 on 2024-01-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0007_customstockrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customstockrecord",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=12, verbose_name="Price"
            ),
        ),
    ]
