# Generated by Django 4.2.6 on 2024-01-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0008_alter_customstockrecord_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customstockrecord",
            options={
                "verbose_name": "CustomStockRecord",
                "verbose_name_plural": "CustomStockRecord",
            },
        ),
        migrations.AlterUniqueTogether(
            name="customstockrecord",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="customstockrecord",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Price",
            ),
        ),
    ]
