# Generated by Django 4.2.6 on 2024-01-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0009_alter_customstockrecord_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stockrecord",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="stockrecord",
            name="discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Discount",
            ),
        ),
        migrations.AddField(
            model_name="stockrecord",
            name="discount_type",
            field=models.CharField(
                blank=True,
                choices=[("percentage", "Percentage"), ("amount", "Amount")],
                max_length=20,
                null=True,
                verbose_name="Discount Type",
            ),
        ),
        migrations.AddField(
            model_name="stockrecord",
            name="mrp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="MRP",
            ),
        ),
        migrations.DeleteModel(
            name="CustomStockRecord",
        ),
    ]
