# Generated by Django 4.2.6 on 2024-01-24 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mycustomapi", "0002_gstgroup_gstsetup"),
        ("partner", "0010_alter_stockrecord_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockrecord",
            name="gst_rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mycustomapi.gstsetup",
            ),
        ),
    ]
