# Generated by Django 4.2.6 on 2024-01-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0011_stockrecord_gst_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockrecord",
            name="base_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="BasePrice",
            ),
        ),
    ]
