# Generated by Django 4.2.6 on 2024-02-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0012_stockrecord_base_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockrecord",
            name="gst_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="GstValue",
            ),
        ),
    ]
