# Generated by Django 4.2.6 on 2024-03-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0014_stockrecord_breadth_stockrecord_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="warehouse_pin",
            field=models.CharField(default="110043", max_length=15),
        ),
    ]
