# Generated by Django 4.2.6 on 2024-06-07 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0016_shippincharge_courier_id"),
        ("credit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credithistory",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="basket.basket",
            ),
        ),
    ]
