# Generated by Django 4.2.6 on 2024-07-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit", "0002_alter_credithistory_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="credithistory",
            name="cart",
        ),
        migrations.AddField(
            model_name="credit",
            name="credit_gst",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="credit",
            name="credit_shipping_type",
            field=models.BooleanField(default=False),
        ),
    ]
