# Generated by Django 4.2.6 on 2024-08-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit", "0005_creditrequestuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditrequestuser",
            name="status",
            field=models.CharField(default="Requested", max_length=20),
        ),
    ]
