# Generated by Django 4.2.6 on 2024-08-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit", "0006_alter_creditrequestuser_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditrequestuser",
            name="reason",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
