# Generated by Django 4.2.6 on 2024-08-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit", "0007_creditrequestuser_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditrequestuser",
            name="erp",
            field=models.BooleanField(default=False),
        ),
    ]
