# Generated by Django 4.2.6 on 2024-08-12 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("credit", "0008_creditrequestuser_erp"),
    ]

    operations = [
        migrations.AddField(
            model_name="credithistory",
            name="credit_request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="credit.creditrequestuser",
            ),
        ),
    ]
