# Generated by Django 4.2.6 on 2024-04-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bannermanagement", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="attribute",
        ),
        migrations.RemoveField(
            model_name="brand",
            name="attribute_value",
        ),
        migrations.AddField(
            model_name="brand",
            name="brand_name",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
