# Generated by Django 4.2.6 on 2024-04-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bannermanagement",
            "0002_remove_brand_attribute_remove_brand_attribute_value_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bannermanagement",
            name="current_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="brand",
            name="current_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="categorypromotion",
            name="current_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="categorypromotionset",
            name="current_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
