# Generated by Django 4.2.6 on 2024-05-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bannermanagement",
            "0003_bannermanagement_current_date_brand_current_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="voucherset",
            name="shipping_charges",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
