# Generated by Django 4.2.6 on 2024-05-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bannermanagement", "0009_remove_voucherset_gstrate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucherset",
            name="shipping_charges",
            field=models.CharField(),
        ),
    ]
