# Generated by Django 4.2.6 on 2024-05-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bannermanagement", "0012_voucherset_is_ship_charge"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucherset",
            name="club_number",
            field=models.CharField(default=1),
        ),
        migrations.AddField(
            model_name="voucherset",
            name="clubable",
            field=models.BooleanField(default=True),
        ),
    ]
