# Generated by Django 4.2.6 on 2024-05-09 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("offer", "0011_rangeproductfileupload_included"),
        ("bannermanagement", "0015_recordcreatedby"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordcreatedby",
            name="conditionoffer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_users",
                to="offer.conditionaloffer",
            ),
        ),
        migrations.AlterField(
            model_name="recordcreatedby",
            name="created_by",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_users_record",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
