# Generated by Django 4.2.6 on 2024-05-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bannermanagement", "0018_voucherrequestuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucherrequestuser",
            name="status",
            field=models.CharField(
                choices=[("Created", "Created"), ("Closed", "Closed")],
                default="Created",
                max_length=12,
            ),
        ),
    ]
