# Generated by Django 4.2.6 on 2024-05-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0031_product_featured_products"),
        ("bannermanagement", "0018_voucherrequestuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucherrequestuser",
            name="select_categories",
            field=models.ManyToManyField(to="catalogue.category"),
        ),
    ]
