# Generated by Django 4.2.6 on 2024-05-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bannermanagement", "0019_alter_voucherrequestuser_select_categories"),
        ("bannermanagement", "0020_alter_voucherrequestuser_select_categories"),
    ]

    operations = []
