# Generated by Django 4.2.6 on 2024-08-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bannermanagement", "0024_voucherrequestuser_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucherset",
            name="amount_type",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "Percentage",
                        "Discount is a percentage off of the product's value",
                    ),
                    (
                        "Absolute",
                        "Discount is a fixed amount off of the product's value",
                    ),
                    ("Multibuy", "Discount is to give the cheapest product for free"),
                    (
                        "Fixed price",
                        "Get the products that meet the condition for a fixed price",
                    ),
                    (
                        "Shipping absolute",
                        "Discount is a fixed amount of the shipping cost",
                    ),
                    ("Shipping fixed price", "Get shipping for a fixed price"),
                    (
                        "Shipping percentage",
                        "Discount is a percentage off of the shipping cost",
                    ),
                ],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="voucherset",
            name="voucher_amount",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=15, null=True
            ),
        ),
    ]
