# Generated by Django 4.2.6 on 2024-09-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bannermanagement", "0025_voucherset_amount_type_voucherset_voucher_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voucherrequestuser",
            name="voucher_request_name",
        ),
        migrations.AddField(
            model_name="voucherrequestuser",
            name="club_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="voucherrequestuser",
            name="gst_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="voucherrequestuser",
            name="shipping_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
