# Generated by Django 4.2.6 on 2024-09-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bannermanagement",
            "0026_remove_voucherrequestuser_voucher_request_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="voucherrequestuser",
            name="type_of_price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
