# Generated by Django 4.2.6 on 2024-09-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bannermanagement", "0027_voucherrequestuser_type_of_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucherrequestuser",
            name="type_of_price",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
