# Generated by Django 4.2.6 on 2024-09-16 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bannermanagement", "0028_alter_voucherrequestuser_type_of_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="FixedVoucherCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_value", models.IntegerField()),
                ("min_value", models.IntegerField()),
                ("fixed", models.BooleanField()),
                (
                    "voucherset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="condition",
                        to="bannermanagement.voucherset",
                    ),
                ),
            ],
        ),
    ]
