# Generated by Django 4.2.6 on 2024-09-17 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bannermanagement", "0029_fixedvouchercondition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fixedvouchercondition",
            name="fixed",
        ),
    ]
