# Generated by Django 4.2.6 on 2024-09-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bannermanagement", "0030_remove_fixedvouchercondition_fixed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voucherrequestuser",
            name="club_type",
        ),
        migrations.RemoveField(
            model_name="voucherrequestuser",
            name="gst_type",
        ),
        migrations.RemoveField(
            model_name="voucherrequestuser",
            name="shipping_type",
        ),
        migrations.RemoveField(
            model_name="voucherrequestuser",
            name="type_of_price",
        ),
        migrations.RemoveField(
            model_name="voucherrequestuser",
            name="voucher_type",
        ),
        migrations.AlterField(
            model_name="voucherrequestuser",
            name="status",
            field=models.CharField(
                choices=[
                    ("Requested", "Requested"),
                    ("Created", "Created"),
                    ("Closed", "Closed"),
                ],
                default="Requested",
                max_length=12,
            ),
        ),
    ]
