# Generated by Django 4.2.6 on 2024-03-15 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("role_permission", "0002_alter_roletype_role_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissions",
            name="non_permitted_url",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="roles",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
