# Generated by Django 4.2.6 on 2024-06-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "role_permission",
            "0003_alter_permissions_non_permitted_url_alter_roles_user",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="roletype",
            name="role_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
