# Generated by Django 4.2.6 on 2024-06-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("role_permission", "0004_alter_roletype_role_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roles",
            name="role",
        ),
        migrations.AddField(
            model_name="roles",
            name="role",
            field=models.ManyToManyField(to="role_permission.roletype"),
        ),
    ]
