# Generated by Django 4.2.6 on 2024-06-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("role_permission", "0005_remove_roles_role_roles_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roles",
            name="role",
            field=models.ManyToManyField(to="role_permission.permissions"),
        ),
    ]
