# Generated by Django 4.2.6 on 2024-06-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("role_permission", "0006_alter_roles_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="permissions",
            name="url_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="RoleType",
        ),
    ]
