# Generated by Django 4.2.6 on 2024-11-05 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("role_permission", "0007_permissions_url_name_delete_roletype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roles",
            name="role",
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_name", models.TextField(blank=True, null=True)),
                (
                    "permission_denied",
                    models.ManyToManyField(to="role_permission.permissions"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="roles",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="role_permission.role",
            ),
        ),
    ]
