# Generated by Django 4.2.6 on 2024-02-25 23:04


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0028_attributeoption_code_attributeoptiongroup_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attributeoption",
            name="code",
        ),
        migrations.RemoveField(
            model_name="attributeoptiongroup",
            name="code",
        ),
        migrations.RemoveField(
            model_name="category",
            name="code",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="code",
        ),
    ]
