# Generated by Django 4.2.6 on 2024-03-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0029_remove_attributeoption_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="specifications",
            field=models.TextField(blank=True, null=True),
        ),
    ]
