# Generated by Django 4.2.6 on 2024-06-10 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0026_orderjson"),
        ("wallet", "0003_wallethistory_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallethistory",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallet",
                to="order.order",
            ),
        ),
    ]
