# Generated by Django 4.2.6 on 2024-02-25 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0015_order_payment_types"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment_types",
        ),
    ]
