# Generated by Django 4.2.6 on 2024-02-26 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0018_razorpay"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="razorpay",
            name="payment_signature",
        ),
    ]
