# Generated by Django 4.2.6 on 2024-03-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0019_remove_razorpay_payment_signature"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="email",
            field=models.EmailField(
                blank=True, max_length=255, null=True, verbose_name="Email"
            ),
        ),
    ]
