# Generated by Django 4.2.6 on 2024-03-28 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0020_shippingaddress_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fship_order_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sales_order_id", models.CharField(max_length=60)),
                ("awb_no", models.CharField(max_length=40)),
                ("api_order_id", models.CharField(max_length=40)),
                ("pick_up_id", models.CharField(max_length=40)),
                ("fship_pick_up_id", models.CharField(max_length=40)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.order",
                    ),
                ),
            ],
        ),
    ]
