# Generated by Django 4.2.6 on 2024-05-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0021_fship_order_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="erp_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
