# Generated by Django 4.2.6 on 2024-06-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0026_orderjson"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="address_type",
            field=models.CharField(
                blank=True,
                choices=[("HOME", "HOME"), ("OFFICE", "OFFICE"), ("OTHER", "OTHER")],
                default="HOME",
                max_length=100,
                null=True,
            ),
        ),
    ]
