# Generated by Django 4.2.6 on 2024-07-18 10:45

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0027_shippingaddress_address_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingaddress",
            name="email",
            field=models.EmailField(
                blank=True, max_length=255, null=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="billingaddress",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="In case we need to call you about your order",
                max_length=128,
                region=None,
                verbose_name="Phone number",
            ),
        ),
    ]
