# Generated by Django 4.2.6 on 2024-10-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0028_billingaddress_email_billingaddress_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="razorpay",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="razorpay",
            name="raz_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("authorized", "authorized"),
                    ("captured", "captured"),
                    ("failed", "failed"),
                    ("NOT_CHECKED", "NOT_CHECKED"),
                ],
                default="NOT_CHECKED",
            ),
        ),
    ]
