# Generated by Django 4.2.6 on 2024-04-29 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mycustomapi", "0004_alter_gstsetup_hsn_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gstsetup",
            options={"ordering": ["-create_date"]},
        ),
    ]
