from django.urls import path
from mycustomapi.views.checkout import failed_order_view

from .views import (
    AddBannerView,
    BannerListView,
    DeleteBannerView,
    BannermanagementAPIView,
    CategoryPromotions,
    LatestProductAPIView,
    ToggleBannerView,
    EditBannerView,
    AddCategoryPromotion,
    CategoryPromotionList,
    DeleteCategoryBannerView,
    EditCategoryBannerView,
    ToggleCategoryBannerView,
    get_subcategories,
    OpenBannerView,
    AddGSTGroup,
    AddGSTSetup,
    manage_brands,
    ManageBrandList,
    DeleteManageBrand,
    EditManageBrand,
    GSTGroupUpdateView,
    GSTGroupDeleteView,
    GSTSetupUpdateView,
    GSTSetupDeleteView,
    vouchersets,
    Addvoucher,
    Editvoucherset,
    ListGSTGroup,
    ListGSTSetup,
    VoucherRequestUserApi,
    VoucherRequestUserList,
    VoucherRequestUserDelete,
    VoucherRequestUserDetails,
    VoucherRequestUserStatus,
    EditCategoryPromotion,
)

urlpatterns = [
    # add main banners
    path(
        "edit-category-promotion/<int:pk>/",
        EditCategoryPromotion.as_view(),
        name="edit-category-promotion",
    ),
    path("add-banner/", AddBannerView.as_view(), name="add-banner"),
    path("banner-list/", BannerListView.as_view(), name="banner-list"),
    path("delete-banner/<int:pk>/", DeleteBannerView.as_view(), name="delete-banner"),
    path("edit-banner/<int:banner_id>/", EditBannerView.as_view(), name="edit-banner"),
    path(
        "toggle-banner/<int:banner_id>/",
        ToggleBannerView.as_view(),
        name="toggle-banner",
    ),
    path(
        "get_child_categories/",
        AddBannerView.get_child_categories,
        name="get_child_categories",
    ),
    path("get_subcategories/", get_subcategories, name="get_subcategories"),
    path("open-banner/<int:set_id>/", OpenBannerView.as_view(), name="open-banner"),
    path(
        "add-categorypromotion/",
        AddCategoryPromotion.as_view(),
        name="add-categorypromotion",
    ),
    path(
        "CategoryPromotionList-list/",
        CategoryPromotionList.as_view(),
        name="CategoryPromotionList-list",
    ),
    path(
        "delete-banner-categ/<int:pk>/",
        DeleteCategoryBannerView.as_view(),
        name="delete-banner-categ",
    ),
    path(
        "edit-banner-categ/<int:banner_id>/",
        EditCategoryBannerView.as_view(),
        name="edit-banner-categ",
    ),
    path(
        "toggle-banner-categ/<int:banner_id>/",
        ToggleCategoryBannerView.as_view(),
        name="toggle-banner-categ",
    ),
    # for forntend react
    path("banners/", BannermanagementAPIView.as_view(), name="banners"),
    path(
        "categories-promotions/",
        CategoryPromotions.as_view(),
        name="categories-promotions",
    ),
    path("latest-product/", LatestProductAPIView.as_view(), name="latest-product"),
    path("gst-group/", AddGSTGroup.as_view(), name="gst-group"),
    path("gst-setup/", AddGSTSetup.as_view(), name="gst-setup"),
    path("gst-group-list/", ListGSTGroup.as_view(), name="gst-group-list"),
    path("gst-setup-list/", ListGSTSetup.as_view(), name="gst-setup-list"),
    path("failed_order/", failed_order_view, name="failed_order"),
    path("manage_brands/", manage_brands, name="manage_brands"),
    path("manage_brands_list/", ManageBrandList.as_view(), name="manage_brands_list"),
    path(
        "manage_brands_edit/<int:brand_id>/",
        EditManageBrand.as_view(),
        name="manage_brands_edit",
    ),
    path(
        "manage_brands_delete/<int:pk>/",
        DeleteManageBrand.as_view(),
        name="manage_brands_delete",
    ),
    # urls.py
    path(
        "gst-group/update-gst-group/<int:pk>/",
        GSTGroupUpdateView.as_view(),
        name="update-gst-group",
    ),
    path(
        "gst-group/delete-gst-group/<int:pk>/",
        GSTGroupDeleteView.as_view(),
        name="delete-gst-group",
    ),
    path(
        "gst-setup/update-gst-setup/<int:pk>/",
        GSTSetupUpdateView.as_view(),
        name="update-gst-setup",
    ),
    path(
        "gst-setup/delete-gst-setup/<int:pk>/",
        GSTSetupDeleteView.as_view(),
        name="delete-gst-setup",
    ),
    path("voucher-sets/", vouchersets.as_view(), name="voucher-sets"),
    path("add-voucher/", Addvoucher.as_view(), name="add-voucher"),
    path(
        "edit-voucherset/<int:voucher_id>/",
        Editvoucherset.as_view(),
        name="edit-voucherset",
    ),
    path(
        "voucher-request-user/",
        VoucherRequestUserApi.as_view(),
        name="voucher-request-user",
    ),
    path(
        "voucher-request-user/<int:pk>/",
        VoucherRequestUserApi.as_view(),
        name="voucher-request-user",
    ),
    path(
        "voucher-request-user-list/",
        VoucherRequestUserList.as_view(),
        name="voucher-request-user-list",
    ),
    path(
        "voucher-request-user-delete/<int:pk>/",
        VoucherRequestUserDelete.as_view(),
        name="voucher-request-user-delete",
    ),
    path(
        "voucher-request-user-details/<int:pk>/",
        VoucherRequestUserDetails.as_view(),
        name="voucher-request-user-details",
    ),
    path(
        "voucher-request-user-status/<int:pk>/",
        VoucherRequestUserStatus.as_view(),
        name="voucher-request-user-status",
    ),
]
