# Generated by Django 4.2.6 on 2024-04-22 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0031_product_featured_products"),
        ("DiscountManagement", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attrname",
            name="attr_name",
        ),
        migrations.AlterField(
            model_name="attrname",
            name="attr_value",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogue.attributeoption",
            ),
        ),
    ]
