# Generated by Django 4.2.6 on 2024-04-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0031_product_featured_products"),
        (
            "DiscountManagement",
            "0002_remove_attrname_attr_name_alter_attrname_attr_value",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="proxyclassforrange",
            name="attr",
            field=models.ManyToManyField(to="catalogue.attributeoption"),
        ),
        migrations.DeleteModel(
            name="AttrName",
        ),
    ]
