# Generated by Django 4.2.6 on 2024-04-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0031_product_featured_products"),
        ("DiscountManagement", "0005_alter_proxyclassforrange_range"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proxyclassforrange",
            name="included_categories",
            field=models.ManyToManyField(
                related_name="proxy_included_categories", to="catalogue.category"
            ),
        ),
    ]
