# Generated by Django 4.2.6 on 2024-05-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DiscountManagement", "0007_proxyclassforrange_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proxyclassforrange",
            name="created_by",
        ),
    ]
