# Generated by Django 4.2.6 on 2024-07-19 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0028_billingaddress_email_billingaddress_phone_number"),
        ("catalogue", "0032_alter_productimage_original"),
        ("DiscountManagement", "0008_remove_proxyclassforrange_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoucherAllocationBYLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("MRP", models.IntegerField()),
                ("listing_price", models.IntegerField()),
                ("voucher_value", models.FloatField()),
                ("unit_price", models.FloatField()),
                ("taxable_amount", models.FloatField()),
                ("gst_value", models.FloatField()),
                ("order_value", models.FloatField()),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voucher_allocation_by_line",
                        to="order.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogue.product",
                    ),
                ),
            ],
        ),
    ]
