# Generated by Django 4.2.6 on 2024-07-19 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0028_billingaddress_email_billingaddress_phone_number"),
        ("DiscountManagement", "0009_voucherallocationbyline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucherallocationbyline",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voucher_allocation_by_line",
                to="order.order",
            ),
        ),
    ]
