# Generated by Django 4.2.6 on 2024-07-19 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0015_partner_warehouse_pin"),
        ("DiscountManagement", "0010_alter_voucherallocationbyline_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucherallocationbyline",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="voucherallocationbyline",
            name="stock",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="partner.stockrecord",
            ),
        ),
    ]
