# Generated by Django 4.2.6 on 2024-07-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DiscountManagement", "0011_voucherallocationbyline_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucherallocationbyline",
            name="shipping",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
