# Generated by Django 4.2.6 on 2024-07-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DiscountManagement", "0012_voucherallocationbyline_shipping"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucherallocationbyline",
            name="tax_type",
            field=models.CharField(
                blank=True,
                choices=[("Inclusive", "Inclusive"), ("Exclusive", "Exclusive")],
                default="Inclusive",
                null=True,
            ),
        ),
    ]
