# Generated by Django 4.2.6 on 2024-07-26 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0016_shippincharge_courier_id"),
        ("DiscountManagement", "0013_voucherallocationbyline_tax_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftCartTotalAMount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_amount", models.FloatField()),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="basket.basket"
                    ),
                ),
            ],
        ),
    ]
