# Generated by Django 4.2.6 on 2024-03-15 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0009_useraddress_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraddress",
            name="email",
        ),
    ]
