# Generated by Django 4.2.6 on 2024-06-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0011_useraddress_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraddress",
            name="address_type",
            field=models.CharField(
                blank=True,
                choices=[("HOME", "HOME"), ("OFFICE", "OFFICE"), ("OTHER", "OTHER")],
                default="HOME",
                max_length=100,
                null=True,
            ),
        ),
    ]
