# Generated by Django 4.2.6 on 2024-02-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0012_line_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="line",
            name="prodcut_gst_tax",
            field=models.FloatField(default=0),
        ),
    ]
