# Generated by Django 4.2.6 on 2024-03-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0015_shippincharge"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippincharge",
            name="courier_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
